Added Card Like structure in experience section
ashutosh1919/masterPortfolio pull request #291
Opened 2023-05-13 15:00 UTC by Vyomrana02

Output for same is
![image](https://github.com/ashutosh1919/masterPortfolio/assets/87069619/548b0134-44cd-470b-8748-e4bf185eb8ee)

2023-05-13 15:05 UTC, saiteja13427 commented
@Vyomrana02 can you add job description as well to the cards (as commented on the issue)

Also can you fix the build warnings so that we can see a deploy preview.

2023-05-15 18:29 UTC, ashutosh1919 commented
@Vyomrana02 why is the workflow failing? @saiteja13427, can you please suggest some changes so that it is successful?

2023-05-16 01:33 UTC, saiteja13427 commented
@ashutosh1919 it is failing due to some build warnings. As we have CI=true, it considers warnings also as errors and fails.

Thus, asked to fix the build warnings.

2023-05-16 18:21 UTC, ashutosh1919 requested changes
Removed unused code

2023-05-16 18:21 UTC, ashutosh1919 commented on src/components/experienceCard/ExperienceCard.js
> +import ProjectLanguages from '../projectLanguages/ProjectLanguages';
```suggestion
```

2023-05-16 18:25 UTC, ashutosh1919 commented
@Vyomrana02 Please add a description to the experience cards. Also, please increase the width of the card to full width of accordian.

2023-05-17 13:56 UTC, Vyomrana02 commented
This will work??

![image](https://github.com/ashutosh1919/masterPortfolio/assets/87069619/59884cf8-8c2a-4c2d-989b-250862488897)

2023-05-17 14:18 UTC, saiteja13427 commented
@Vyomrana02 Looks good, maybe decrease the gap above the description a little bit and push the code so that we can check the deploy preview!

2023-05-17 14:31 UTC, Vyomrana02 commented
Hello I am facing issue with the vertical line size and content size in card.
card grows or shrinks acc. to content but the height of vertical line is fixed so sometimes overlap or makes space.
1 Option to solve this:-
1. setting the constant height of cards for all so no overlapping or space .
 what should I do??

2023-05-22 14:25 UTC, ashutosh1919 commented
@Vyomrana02 please push the code so that we can have a look. @saiteja13427 , please help him once he pushes the code.

2023-05-22 18:13 UTC, saiteja13427 commented
Yes @Vyomrana02 Please push the code, Let me look into it and find a solution!

2023-05-23 02:58 UTC, closed without merging

2023-05-23 02:59 UTC, Vyomrana02 commented
dynamic size of card output
![image](https://github.com/ashutosh1919/masterPortfolio/assets/87069619/88a2876d-a8e2-4995-8a3d-d1ea926d155e)

I have pushed into this fork :-
https://github.com/Vyomrana02/masterPortfolio
changes in experiencecard.js

2023-05-23 04:25 UTC, saiteja13427 commented
@Vyomrana02 Why did you close this PR?
Can you open a new fresh PR with only the experience card changes, so that we can check the deployment preview?